# Generated by Django 3.2.5 on 2021-07-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('status', models.CharField(choices=[('OP', 'Открыта'), ('IN', 'В работе'), ('CL', 'Закрыта')], default='OP', max_length=2, verbose_name='Статус')),
                ('type_app', models.CharField(choices=[('AD', 'Консультация'), ('RE', 'Ремонт'), ('SE', 'Обслуживание')], default='AD', max_length=2, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
